/** Stable task identity allocated monotonically within a TaskManager. */
export type TaskId = `t${number}`;

/** The execution surface responsible for a task. */
export type TaskKind = "tool" | "subagent" | "scheduled";

/**
 * Durable lifecycle state. Running work exists in-process; scheduled work is
 * represented only by its wall-clock wake time and can survive process exit.
 */
export type TaskStatus = "running" | "scheduled" | "completed" | "failed" | "stopped" | "lost";

/** Caller-supplied explanation used by executors to classify an abort. */
export type TaskStopReason = string;

/** The serializable task shape shared by runtime, persistence, protocol, and UI code. */
export interface TaskDescriptor {
  /** Monotonic identity generated by the manager, including across recovery. */
  id: TaskId;
  /** Selects whether the task is in-process work or a durable scheduled wait. */
  kind: TaskKind;
  /** Stable machine-facing name for logs and task listings. */
  name: string;
  /** Human-facing text describing the concrete work in progress. */
  label: string;
  /** Scope whose closure owns and cascade-stops this task. */
  ownerScopeId: string;
  /** Current lifecycle state; terminal states never transition again. */
  status: TaskStatus;
  /** Unix-epoch timestamp recorded when the task was created. */
  startedAt: number;
  /** Unix-epoch wake time, present only for scheduled tasks. */
  wakeAt?: number;
}

/** A terminal value emitted exactly once and queued by settlement time. */
export type TaskSettlement =
  | { id: TaskId; status: "completed"; settledAt: number; result: unknown }
  | { id: TaskId; status: "failed"; settledAt: number; error: unknown }
  | { id: TaskId; status: "stopped"; settledAt: number; reason: TaskStopReason }
  | { id: TaskId; status: "lost"; settledAt: number };

/** Observable task state, including buffered values rather than derived counts. */
export interface TaskSnapshot {
  /** Copy of the durable descriptor at the time of inspection. */
  descriptor: TaskDescriptor;
  /** Ordered output chunks retained for later task_output inspection. */
  output: readonly string[];
  /** Terminal value once the task has settled. */
  settlement?: TaskSettlement;
}

/** Events emitted synchronously after each externally observable task change. */
export type TaskEvent =
  | { type: "started"; descriptor: TaskDescriptor }
  | { type: "output"; id: TaskId; chunk: string }
  | { type: "settled"; settlement: TaskSettlement };
