/**
 * Core types for duet-agent.
 *
 * The key architectural insight: memories and interrupts are not optional
 * modules — they're woven into every agent turn. An agent without memory is
 * stateless. An agent that can't be interrupted can't collaborate.
 */

import type { Model } from "@mariozechner/pi-ai";
import type { Skill, loadSkills } from "@mariozechner/pi-coding-agent";
import type { MemoryStore } from "../memory/store.js";

/** Directly mirrors pi-coding-agent's loadSkills options so callers can pass through upstream discovery settings. */
export type SkillDiscoveryOptions = Partial<Parameters<typeof loadSkills>[0]>;

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

/** Every entity in the system gets a typed ID. */
export type SessionId = string & { readonly __brand: "SessionId" };
export type AgentId = string & { readonly __brand: "AgentId" };
export type TaskId = string & { readonly __brand: "TaskId" };
export type MemoryId = string & { readonly __brand: "MemoryId" };

// ---------------------------------------------------------------------------
// Memory (native — not a plugin)
// ---------------------------------------------------------------------------

/** Controls ordering and filtering when memories are recalled or rendered. */
export type ObservationPriority = "high" | "medium" | "low";
/** Defines whether an observation applies only to this session or to the broader resource/project. */
export type ObservationScope = "session" | "resource";
/** Records why reflection ran when observation logs are condensed. */
export type ReflectionMode = "none" | "threshold" | "forced";

export type ObservationSource =
  | { kind: "user" }
  | { kind: "agent"; agentId: AgentId }
  | { kind: "system" }
  | { kind: "tool"; toolName: string };

/**
 * A distilled memory produced by the observer and later rendered back into model
 * context. Observations are the durable replacement for older raw messages once
 * context activation runs.
 */
export interface Observation {
  id: MemoryId;
  sessionId: SessionId;
  createdAt: number;
  observedDate: string;
  /** Concrete date referenced by the content, when that differs from observedDate. */
  referencedDate?: string;
  /** Original phrase such as "tomorrow" or "last week"; useful when exact dating is lossy. */
  relativeDate?: string;
  timeOfDay?: string;
  priority: ObservationPriority;
  scope: ObservationScope;
  source: ObservationSource;
  content: string;
  /** Optional labels for recall filters or external persistence modules. */
  tags: string[];
}

/**
 * Text serialization of an AgentMessage retained by memory until the observer
 * replaces older context with observations. IDs must stay stable so the actor
 * can keep the correct raw tail after activation.
 */
export interface RawMemoryMessage {
  id: MemoryId;
  sessionId: SessionId;
  createdAt: number;
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  estimatedTokens?: number;
}

/** Complete memory view callers can persist and pass back into Orchestrator.run for restore. */
export interface ObservationalMemorySnapshot {
  sessionId: SessionId;
  observations: Observation[];
  rawMessages: RawMemoryMessage[];
  estimatedTokens: {
    observations: number;
    rawMessages: number;
  };
  updatedAt: number;
}

/** Runtime settings for observation, buffering, reflection, and actor-context injection. */
export interface ObservationalMemorySettings {
  /** Turns the transform on or off without changing the rest of the config shape. */
  enabled: boolean;
  /** Default scope assigned to observations generated by the memory transform. */
  scope: ObservationScope;
  /** Fallback model for observer and reflector when their nested model is omitted. */
  model?: Model<any>;
  /** Observer settings: raw messages -> observations. */
  observation: {
    /** Model used to extract observations from raw message batches. */
    model?: Model<any>;
    /** Raw-message token threshold that triggers observation activation and context trimming. */
    messageTokens: number;
    /** Maximum raw-message tokens sent to a single observer call. */
    maxTokensPerBatch: number;
    /** Fraction of messageTokens retained as raw tail after activation. */
    bufferActivation: number;
    /** Optional hard limit for blocking observation work after this many tokens. */
    blockAfter?: number;
    /** Optional budget for including prior observations in observer prompts; false disables it. */
    previousObserverTokens?: number | false;
    /** Additional observer instructions appended to the generated system prompt. */
    instruction?: string;
    /** Ask the observer to emit a short thread/session title. */
    threadTitle?: boolean;
  };
  /** Reflector settings: observations -> condensed observations. */
  reflection: {
    /** Model used to condense the observation log. */
    model?: Model<any>;
    /** Observation-token threshold that triggers reflection. */
    observationTokens: number;
    /** Fraction of observationTokens targeted after reflection compacts the log. */
    bufferActivation: number;
    /** Optional hard limit for blocking reflection work after this many observation tokens. */
    blockAfter?: number;
    /** Additional reflector instructions appended to the generated system prompt. */
    instruction?: string;
  };
  /** Reserved for retrieval modules; current in-memory store uses text scoring, not vector persistence. */
  retrieval?: boolean | { vector?: boolean; scope?: ObservationScope };
  /** Whether observation and raw-tail budgets should share one context budget. */
  shareTokenBudget: boolean;
  /** Whether rendered observations should include temporal markers for model reasoning. */
  temporalMarkers: boolean;
  /** Optional idle-time trigger for activating observations after a quiet period. */
  activateAfterIdle?: number;
  /** Whether provider/model changes should force observation activation. */
  activateOnProviderChange: boolean;
}

/** Query used by planning, guardrails, and actor context to retrieve relevant observations. */
export interface ObservationQuery {
  sessionId?: SessionId;
  query?: string;
  tags?: string[];
  scope?: ObservationScope;
  limit?: number;
  /** Drop observations below this priority. */
  minPriority?: ObservationPriority;
}

/** Events emitted by the default MemoryStore so persistence can be built outside the harness. */
export type MemoryStoreEvent =
  | { type: "raw_message_appended"; message: RawMemoryMessage }
  | { type: "observation_appended"; observation: Observation }
  | { type: "raw_messages_replaced"; sessionId: SessionId; messages: RawMemoryMessage[] }
  | { type: "observations_replaced"; sessionId: SessionId; observations: Observation[] };

export type MemoryStoreEventHandler = (event: MemoryStoreEvent) => void;

/**
 * Narrow extension point for memory persistence. Runtime memory remains the
 * concrete MemoryStore. Persistence modules hydrate that store before a run,
 * then subscribe to events for external serialization or sync.
 */
export interface MemoryPersistenceModule {
  load?(store: MemoryStore): void | Promise<void>;
  subscribe?(store: MemoryStore): void | (() => void);
}

// ---------------------------------------------------------------------------
// Interrupts (native — not a plugin)
// ---------------------------------------------------------------------------

/** The different sources that can interrupt an agent. */
export type InterruptSource =
  | { kind: "user"; message: string }
  | { kind: "environment"; source: string; payload: string }
  | { kind: "agent"; agentId: AgentId; message: string }
  | { kind: "guardrail"; rule: string; message: string }
  | { kind: "timeout" };

export interface Interrupt {
  id: string;
  timestamp: number;
  source: InterruptSource;
  /** Whether this interrupt should pause the current agent turn. */
  priority: "pause" | "queue" | "info";
}

export interface InterruptBus {
  /** Emit an interrupt. */
  emit(interrupt: Omit<Interrupt, "id" | "timestamp">): void;
  /** Subscribe to interrupts. Returns an unsubscribe function. */
  on(handler: (interrupt: Interrupt) => void): () => void;
  /** Wait for the next interrupt matching a predicate. */
  waitFor(predicate: (interrupt: Interrupt) => boolean, timeoutMs?: number): Promise<Interrupt>;
  /** Drain all queued interrupts. */
  drain(): Interrupt[];
}

// ---------------------------------------------------------------------------
// Guardrails (optional but integrated)
// ---------------------------------------------------------------------------

export interface GuardrailResult {
  allowed: boolean;
  reason?: string;
  /** If not allowed, suggest an alternative action. */
  suggestion?: string;
}

export interface Guardrail {
  name: string;
  description: string;
  /** Evaluate whether an action is allowed. */
  evaluate(context: GuardrailContext): Promise<GuardrailResult>;
}

export interface PatternGuardrailRuleConfig {
  pattern: RegExp;
  action: "block" | "warn";
  reason: string;
}

/**
 * Config objects for extending the internal guardrail firewall. The harness
 * owns guardrail construction; callers describe extra policies instead of
 * passing instantiated guardrail classes.
 */
export type GuardrailConfig =
  | { kind: "pattern"; rules: PatternGuardrailRuleConfig[] }
  | { kind: "semantic"; model: Model<any>; policy: string };

export interface GuardrailContext {
  /** The agent attempting the action. */
  agentId: AgentId;
  /** What the agent wants to do. */
  action: string;
  /** The full command or content being evaluated. */
  content: string;
  /** Relevant observations for context. */
  memories: Observation[];
  /** Current session state. */
  sessionState: SessionState;
}

// ---------------------------------------------------------------------------
// Session State Machine (the heart of multi-agent orchestration)
// ---------------------------------------------------------------------------

export type TaskStatus = "pending" | "in_progress" | "completed" | "failed" | "blocked";

/**
 * Task purity classification. The orchestrator determines this during planning.
 *
 * - "pure": no side effects — reads files, analyzes code, generates plans.
 *   Pure tasks with satisfied dependencies are auto-parallelized.
 * - "effectful": has side effects — writes to external systems, sends emails,
 *   updates CRM records, modifies infrastructure. Effectful tasks run
 *   sequentially and may require user confirmation.
 */
export type TaskPurity = "pure" | "effectful";

/** A task in the orchestrator's plan. Sub-agents execute tasks. */
export interface Task {
  id: TaskId;
  /** Human-readable description of what needs to be done. */
  description: string;
  /** The dynamically-defined agent spec that should execute this. */
  agentSpec: SubAgentSpec;
  /** Current status. */
  status: TaskStatus;
  /** IDs of tasks that must complete before this one starts. */
  dependencies: TaskId[];
  /**
   * Whether this task is pure (no side effects) or effectful.
   * Pure tasks are auto-parallelized. Effectful tasks run sequentially.
   */
  purity: TaskPurity;
  /** For effectful tasks: what external system is affected. */
  sideEffectDescription?: string;
  /** Result produced by the sub-agent (if completed). */
  result?: string;
  /** Error message (if failed). */
  error?: string;
  /** Memories created during this task's execution. */
  memoriesCreated: MemoryId[];
}

/**
 * The session state machine. The orchestrator creates and modifies this;
 * sub-agents execute tasks and produce state transitions.
 * This is NOT a tool-call graph — it's a living document.
 */
export interface SessionState {
  sessionId: SessionId;
  /** The original user goal. */
  goal: string;
  /** Current phase of execution. */
  phase: "planning" | "executing" | "evaluating" | "complete" | "interrupted";
  /** The task graph. Orchestrator builds this; sub-agents consume it. */
  tasks: Task[];
  /** Global context available to all agents in this session. */
  context: Record<string, unknown>;
  /** Accumulated memories from this session. */
  sessionMemories: MemoryId[];
  /** History of state transitions for debugging/replay. */
  transitions: StateTransition[];
}

export interface StateTransition {
  timestamp: number;
  fromPhase: SessionState["phase"];
  toPhase: SessionState["phase"];
  trigger: string;
  agentId?: AgentId;
  taskId?: TaskId;
}

/**
 * Runtime continuation input for resuming an orchestration state machine.
 * This hydrates the opinionated in-memory runtime; persistence still lives in
 * external modules via MemoryPersistenceModule.
 */
export interface OrchestratorRunOptions {
  /** Existing session state to continue instead of creating a fresh session. */
  state?: SessionState;
  /** Existing observational memory snapshot to overlay onto the runtime store. */
  memory?: Partial<ObservationalMemorySnapshot>;
  /** Convenience input for callers that only have the current raw message list. */
  messages?: RawMemoryMessage[];
  /** Which phase to resume from. "auto" follows state.phase. */
  resume?: "auto" | "plan" | "execute" | "evaluate";
}

// ---------------------------------------------------------------------------
// Sub-Agent Specification (dynamically defined by orchestrator)
// ---------------------------------------------------------------------------

/**
 * Sub-agents are not pre-built classes — the orchestrator defines them
 * dynamically based on the task at hand. This spec is all a sub-agent
 * needs to know about itself.
 */
export interface SubAgentSpec {
  /** Unique agent ID for this execution. */
  id: AgentId;
  /** What this agent's role is (e.g., "code-writer", "researcher"). */
  role: string;
  /** System prompt for this agent — written by the orchestrator. */
  instructions: string;
  /** Which model to use. */
  model: Model<any>;
  /** Which pi coding tools this agent is allowed to use. */
  allowedActions: string[];
  /** Max turns before the agent must yield. */
  maxTurns: number;
  /** Memory scope: what memories this agent can access. */
  memoryAccess: "all" | "session" | "none";
}

// ---------------------------------------------------------------------------
// Communication Layer (decoupled from agent logic)
// ---------------------------------------------------------------------------

/**
 * The comm layer is how the system talks to the user. It's completely
 * decoupled from agent logic — you can swap text chat for voice, video
 * stream analysis, or anything else.
 */
export interface CommLayer {
  /** Send a message to the user. */
  send(message: CommMessage): Promise<void>;
  /** Receive the next message from the user. Blocks until available. */
  receive(): Promise<CommMessage>;
  /** Subscribe to incoming messages. */
  onMessage(handler: (message: CommMessage) => void): () => void;
  /** Signal that the agent is working (typing indicator, etc). */
  sendStatus(status: AgentStatus): Promise<void>;
}

export type CommMessage =
  | { kind: "text"; content: string }
  | { kind: "file"; path: string; mimeType: string }
  | { kind: "structured"; data: Record<string, unknown> }
  | { kind: "error"; message: string };

export type AgentStatus =
  | { kind: "idle" }
  | { kind: "thinking"; description?: string }
  | { kind: "executing"; taskId: TaskId; description?: string }
  | { kind: "waiting"; reason: string };

// ---------------------------------------------------------------------------
// Agent Harness Config
// ---------------------------------------------------------------------------

export interface DuetAgentConfig {
  /** The orchestrator model (should be the smartest available). */
  orchestratorModel: Model<any>;
  /** Default model for sub-agents. Orchestrator can override per-task. */
  defaultSubAgentModel: Model<any>;
  /** Observational memory tuning. Memory is always enabled; this only adjusts thresholds and models. */
  memory?: Partial<ObservationalMemorySettings>;
  /** Optional persistence/sync modules that subscribe to MemoryStore events. */
  memoryPersistence?: MemoryPersistenceModule[];
  /** Working directory for pi coding tools and project skill discovery. */
  cwd?: string;
  /** Communication layer. */
  comm: CommLayer;
  /** Additional guardrail policies layered on top of the harness defaults. */
  guardrails?: GuardrailConfig[];
  /** Max concurrent sub-agents (only applies to pure tasks). */
  maxConcurrency?: number;
  /** Global system instructions prepended to all agents. */
  systemInstructions?: string;
  /** Skills available to all agents. Loaded at init time. */
  skills?: Skill[];
  /** Skill discovery options. Defaults to ~/.agents/skills and <cwd>/.agents/skills. */
  skillDiscovery?: SkillDiscoveryOptions;
  /** Called on every state transition (for logging, UI, etc). */
  onTransition?: (transition: StateTransition, state: SessionState) => void;
  /** Called when an interrupt is received. */
  onInterrupt?: (interrupt: Interrupt) => void;
}
